name: Maven CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build
        run: mvn clean compile

      - name: Run Tests
        run: mvn test

      - name: Package Application
        run: mvn package

      - name: Deployment Successful
        if: success()
        run: echo "Deployment successfully!"

      - name: Deployment Failed
        if: failure()
        run: echo "Deployment Failed
